"""Shared constants for record exports."""

SERIAL_NUMBER_HEADER = "Serial Number"
NAME_MARATHI_HEADER = "Name (Marathi)"
NAME_ENGLISH_HEADER = "Name (English)"
CONTRIBUTION_AMOUNT_HEADER = "Contribution Amount"
PLACE_MARATHI_HEADER = "Place (Marathi)"
PLACE_ENGLISH_HEADER = "Place (English)"

EXPORT_HEADERS = [
    SERIAL_NUMBER_HEADER,
    NAME_MARATHI_HEADER,
    NAME_ENGLISH_HEADER,
    CONTRIBUTION_AMOUNT_HEADER,
    PLACE_MARATHI_HEADER,
    PLACE_ENGLISH_HEADER,
]

TOTAL_LABEL = "TOTAL"
